language: android

android:
    components:
        - platform-tools
        - tools
        - android-23
        - build-tools-23.0.3
        - extra-android-support
        - extra-android-m2repository

licenses:
    - 'android-sdk-license-.+'

install: true

script: ./gradlew clean build --info --stacktrace

notifications:
    email: false

sudo: false

cache:
    directories:
        - $HOME/.gradle
        - $HOME/.m2